nodes:
  # Wazuh indexer nodes
  indexer:
    - name: wazuh.indexer
      ip: "wazuh.indexer"

  # Wazuh manager nodes
  server:
    - name: wazuh.manager
      ip: "wazuh.manager"

  # Wazuh dashboard nodes
  dashboard:
    - name: wazuh.dashboard
      ip: "wazuh.dashboard"
